# Generated by Django 4.0.3 on 2022-09-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=50)),
                ('quantite', models.IntegerField(default=0)),
                ('prix', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.PositiveIntegerField(default=0)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.PositiveIntegerField(default=0)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
    ]
